
target_dc: "target_dc"

vsphere_data_sources:
  - data_source: vsphere_datacenter
    ds_name: "{{ target_dc }}"
    name: var.deploy_vsphere_datacenter
  - data_source: vsphere_datastore
    ds_name: target_datastore
    name: var.deploy_vsphere_datastore
    datacenter_id: data.vsphere_datacenter.{{ target_dc }}.id
  - data_source: vsphere_compute_cluster
    ds_name: target_cluster
    name: var.deploy_vsphere_cluster
    datacenter_id: data.vsphere_datacenter.{{ target_dc }}.id
  - data_source: vsphere_network
    ds_name: target_network
    name: var.deploy_vsphere_network
    datacenter_id: data.vsphere_datacenter.{{ target_dc }}.id
  - data_source: vsphere_virtual_machine
    ds_name: source_template
    name: var.guest_template
    datacenter_id: data.vsphere_datacenter.{{ target_dc }}.id
